spring:
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3BLR25sRW9JbGV1UGdVaVQKT3FuWVdNbUFzS3ZRRFRJVG9BQXNacTB2RE4yaFJBTkNBQVJwRzVZM3g0UmlubXN5TmpWRTJtcGpIeVA4cVZ4OApJRCtUbnM4ZTZ5MWRNNjVRSnI1UnVKTzVISmhyeEFBb1ZFR3Z0SXo1REFQQmtWbHBkaDB4K1RodwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNERENDQWJPZ0F3SUJBZ0lSQUxPYjZHR3c5eVlnTTZsd3BkWVgxWVV3Q2dZSUtvWkl6ajBFQXdJd1l6RWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1Sd3dHZ1lEVlFRTERCTnliMjkwUUdWNApaV2R2YkMxa1pXWmhkV3gwTVNNd0lRWURWUVFEREJwdGEyTmxjblFnY205dmRFQmxlR1ZuYjJ3dFpHVm1ZWFZzCmREQWVGdzB5TmpBME1UVXhNak13TlRsYUZ3MHlPREEzTVRVeE1qTXdOVGxhTUVjeEp6QWxCZ05WQkFvVEhtMXIKWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JqWlhKMGFXWnBZMkYwWlRFY01Cb0dBMVVFQ3d3VGNtOXZkRUJsZUdWbgpiMnd0WkdWbVlYVnNkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCR2tibGpmSGhHS2VhekkyCk5VVGFhbU1mSS95cFhId2dQNU9leng3ckxWMHpybEFtdmxHNGs3a2NtR3ZFQUNoVVFhKzBqUGtNQThHUldXbDIKSFRINU9IQ2paREJpTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBZgpCZ05WSFNNRUdEQVdnQlJ1WEJ4MU4xTUxzT0p2RGFKUjQ3UlNQRStkZURBYUJnTlZIUkVFRXpBUmdnOXNiMk5oCmJDNHdlR1JpWlM1a1pYWXdDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdGUk9sL2NXMUVYVXQzODl2MWRYcC9CRHIKZms4dEFkQkgrbDZNZ25uNDNVWUNJRFZ6UTdjcWhia0tJT0tLV2J5VUVnNTk4MThUbnBidkh3Tkx0ZExUUFN1UAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
          trustore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNDakNDQWErZ0F3SUJBZ0lRVTNKWUdkR2pTOFRkUzIvVmtYbGx6ekFLQmdncWhrak9QUVFEQWpCak1SNHcKSEFZRFZRUUtFeFZ0YTJObGNuUWdaR1YyWld4dmNHMWxiblFnUTBFeEhEQWFCZ05WQkFzTUUzSnZiM1JBWlhobApaMjlzTFdSbFptRjFiSFF4SXpBaEJnTlZCQU1NR20xclkyVnlkQ0J5YjI5MFFHVjRaV2R2YkMxa1pXWmhkV3gwCk1CNFhEVEkyTURReE5URXlNekExT1ZvWERUTTJNRFF4TlRFeU16QTFPVm93WXpFZU1Cd0dBMVVFQ2hNVmJXdGoKWlhKMElHUmxkbVZzYjNCdFpXNTBJRU5CTVJ3d0dnWURWUVFMREJOeWIyOTBRR1Y0WldkdmJDMWtaV1poZFd4MApNU013SVFZRFZRUUREQnB0YTJObGNuUWdjbTl2ZEVCbGVHVm5iMnd0WkdWbVlYVnNkREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkpWVGxVa3hMbHE3cVVsS3d6QmFzaFJLK3A4d0ZXb0pNbXhuQk5oc05hMXUKQ3hLTy94c2pPK28xRlJ2WC9WaTRiemR0SEFQNVI0azRudERyVlFsV2YxNmpSVEJETUE0R0ExVWREd0VCL3dRRQpBd0lDQkRBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEdBMVVkRGdRV0JCUnVYQngxTjFNTHNPSnZEYUpSCjQ3UlNQRStkZURBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXhBVndUdXZDdXhWTjAzRytQTWNXSDBYeElsM2cKWEZJK0RJTVlOeFpHYnRJQ0lRRFJROGIvNmhKOG0zSWk2TWFxdnZlR2twOEhaMm1yMmY1TjdndHVaaG12bUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8443
  ssl:
    bundle: web
  # Step 5: Configure session cookie with SameSite attribute
  # ...
  # Step 5: End of session cookie configuration
