name: security
on:
  workflow_dispatch
permissions:
  # Required to upload SARIF file to CodeQL.
  actions: read
  # Require writing security events to upload SARIF file
  security-events: write
  # to fetch code (actions/checkout)
  contents: read
